In [15]:
import numpy as np

arr= np.arange(1,10)
flat = arr.flatten()
print(flat)
print(flat)






[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [16]:
print(flat)

[1 2 3 4 5 6 7 8 9]


In [18]:
print(flat[0])

1


In [19]:
flat


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# slicing performed as a list 
print(flat[3])
print(flat[3:5])
print(flat[3:15])
print(flat[3:])
print(flat[:])


4
[4 5]
[4 5 6 7 8 9]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [58]:
#  slicing return a view not a copy ! change affect the orginalarray
b= flat[3:6].copy()   # [1, 2, 3, 4, 5, 6, 7, 8, 9]
b[0]=234        #[4,5]
print(flat)   # [  1   2   3 234   5   6   7   8   9] changed


[  1   2   3 234   5   6   7   8   9]


In [71]:
#  to make a copy of array we use np.copy
b= flat[3:6].copy()  # [1, 2, 3, 4, 5, 6, 7, 8, 9]
b[1]=400     #[4,5]
print(flat)   #[1 2 3 4 5 6 7 8 9]  not changed
print(b)       #[  4 400   6]



[1 2 3 4 5 6 7 8 9]
[  4 400   6]


In [74]:
# Fancing indexing 
arr= np.array([2,32,24,65,88,87,56,54])


In [76]:
index=[2,3,4,5]  
print(arr[index])   #[24 65 88 87]  fancing indexing

[24 65 88 87]


In [79]:
# boolean masking (filter data)
mask =arr>30
arr[mask]  #array([32, 65, 88, 87, 56, 54])
arr[arr>50]   # array([65, 88, 87, 56, 54])


array([65, 88, 87, 56, 54])