In [ ]:
import numpy as np
# 1D array 
arr=np.array([1,2,3,4,5])
print(arr)

# 2D array 
arr2d= np.array([[2,3,2,3],[3,2,3,2]])
print(arr2d)
print(type(arr))

print(arr.shape)
print(arr.size)
print(arr2d.shape)
print(arr2d.size)



[1 2 3 4 5]
[[2 3 2 3]
 [3 2 3 2]]
<class 'numpy.ndarray'>
(5,)
5
(2, 4)
8
