In [4]:
# Now, we’ll explore how to make your code faster
# with vectorization and broadcasting in NumPy.
# These techniques are key to boosting performance 
# in numerical operations by avoiding slow loops and memory inefficiency.
import numpy as np

# 1 vectorization 
arr = np.array([2,32,2,1])
arr=arr**2
print(arr)




[   4 1024    4    1]


In [5]:
# Scaling Arrays Without Extra Memory
arr= np.array([2,1,2,1])
arr= arr+10   # broadcasting 10 is added to all element 
print(arr)

[12 11 12 11]


In [11]:
# . Broadcasting with Arrays of Different Shapes

# arr = np.array([2,32,2,1])
# arr1 = np.array([2,3,3,2])
# arr= arr+arr1
# print(arr)

arr2D = np.array( [[2,32,2,1] , [2,3,3,2]])
arr1 = np.array([2,3,3,2])
arr= arr2D+arr1
print(arr)

[[ 4 35  5  3]
 [ 4  6  6  4]]


In [15]:
# Hands-on: Applying Broadcasting to Real-World Scenarios

# ----> Normalizing Data Using Broadcasting
arr= np.array([
       [5,5,2],
       [2,4,2],
       [8,3,8],
       [1,7,2]  
])
mean = arr.mean(axis=0)
std= arr.std(axis=0)
normalized = (arr-mean)/std
print(normalized)
# •	Broadcasting enables operations between arrays
# of different shapes by automatically stretching the smaller array to 
# match the shape of the larger array, without creating additional copies.



[[ 0.36514837  0.16903085 -0.57735027]
 [-0.73029674 -0.50709255 -0.57735027]
 [ 1.46059349 -1.18321596  1.73205081]
 [-1.09544512  1.52127766 -0.57735027]]
