In [3]:
# Data type in numpy 
import numpy as np 
arr= np.array([1,2,2,3,])
print(arr.dtype)

int64


In [5]:
arr.astype("float64")

array([1., 2., 2., 3.])

In [8]:

arr= np.array([2,32,3,2], dtype="float64")
arr

array([ 2., 32.,  3.,  2.])

In [9]:
arr

array([ 2., 32.,  3.,  2.])

In [10]:
print(arr.dtype)

float64


In [11]:
con_into =arr.astype("int64")

In [12]:
con_into

array([ 2, 32,  3,  2])

In [16]:
# checking memory uses 
arr1= np.array([2,32,2,2], dtype="int32")
arr2= np.array([2,32,2,2], dtype="int64")
print(arr1.nbytes)
print(arr2.nbytes)

16
32


In [18]:
#  string in numpy
# basically we do not use string in numpy becoz it is less effiesient
arrStr= np.array(["sunil" ,"sona" , "meka"] , )
print(arrStr)
print(arrStr.dtype)


['sunil' 'sona' 'meka']
<U5


In [20]:
# complex number in numpy
arr1 = np.array([1+2j, 2+3j,3+4j], dtype="complex64")
arr2 = np.array([1+2j, 2+3j,3+4j],dtype="complex128")
print(arr)
print(arr.dtype)

[1.+2.j 2.+3.j 3.+4.j]
complex128


In [27]:
#  object data types in numypy
arr= np.array([{'a':1} , [2,3,4] ,"sunil"],dtype= "object"  )
print(arr[0]['a'])
print(arr.dtype)

1
object
