In [5]:
import numpy as np
arr2D= np.array([
    [2,3,2],
    [2,4,5],
    [8,9,0]
]
)



In [10]:
arr2D
arr2D[0]

array([2, 3, 2])

In [15]:
# np.sum(arr2D,axis=0)
arr2D.sum(axis=0)
arr2D.sum(axis=1)


array([ 7, 11, 17])

In [15]:
# indexing in multidimensional array
import numpy as np
arr2D= np.array([
    [2,3,2],
    [2,4,5],
    [8,9,0]
])      # array([ [2, 3, 2],[2, 4, 5],[8, 9, 0]])
print(arr2D[0:2])
# 2 
print(arr2D[0:1,0:2])     #[[2 3]]  return common of both operation
                
print(arr2D[0][1])    # 2
print(arr2D[1,1])     # 4
print(arr2D[2,2])     #  0


[[2 3 2]
 [2 4 5]]
[[2 3]]
3
4
0
