In [ ]:

1.Write code to split the array [10,20,30,40,50,60] into 3 equal parts.
2.Generate a 2x4 matrix with random integers between 1 and 20.
3.Write NumPy code to vertically stack:
[1,2,3] 
[4,5,6] 
4.Generate 5 random numbers between 0 and 1 using NumPy.
5.Write a code to calculate the determinant of matrix:














In [2]:
# 1.Write code to split the array [10,20,30,40,50,60] into 3 equal parts.
import numpy as np
arr= np.array([10,20,30,40,50,60])
arr1=np.split(arr,3)
print(np.split(arr,3))
print(arr1)

[array([10, 20]), array([30, 40]), array([50, 60])]
[array([10, 20]), array([30, 40]), array([50, 60])]


In [7]:
# Generate a 2x4 matrix with random integers between 1 and 20.
arr= np.random.randint(1,20,8).reshape(2,4)
print(arr)

[[11 12  3  3]
 [ 8 10 19  8]]


In [10]:
# 3.Write NumPy code to vertically stack:
# [1,2,3] 
# [4,5,6] 
arr1= np.array([1,2,3] )
arr2= np.array([4,5,6])
print(np.vstack([arr1,arr2]))
print(np.hstack([arr1,arr2]))


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
# .Generate 5 random numbers between 0 and 1 using NumPy.


In [17]:
# .Write a code to calculate the determinant of matrix:

arr= np.array([[2,3,4] ,[4,2,5] , [5,4,3]] )
det= np.linalg.det(arr)
print(det)



34.99999999999999
