In [25]:
#  3 D Array 
import numarr.shappy as np
arr= np.array(
    [  [ [2,4,5] ,[8,2,6]] ,
       [[8,4,9] , [2,4,3]]
    ]
)
print(e)



(2, 2, 3)


In [22]:
print(arr[0][1][1])
print(arr[:,0,: ])

2
[[2 4 5]
 [8 4 9]]


In [27]:
print(arr[:,0,0])
print(arr[1,0,:])


[2 8]
[8 4 9]


In [35]:
fla=arr[:,0]
print(fla)

[[2 4 5]
 [8 4 9]]


In [1]:
# changing along the axis ----
# arr= np.array(
#     [  [ [2,4,5] ,[8,2,6]] ,
#        [[8,4,9] , [2,4,3]]
#     ]
# )

# arr[0,:,1]=2
arr[:,0]=2

# arr[:,:,:]=0
print(arr)

NameError: name 'arr' is not defined

In [11]:
import numpy as np
arr= np.array(
    [  [ [2,4,5] ,[8,2,6]] ,
       [[8,4,9] , [2,4,3]]
    ]
)
print(arr[0,:,:])
print(arr[:,0,0])

[[2 4 5]
 [8 2 6]]
[2 8]
