In [32]:
#  array in numpy
#  creating array from scratch 
import numpy as np

# 1 fill all element with zeroes
# arr1= np.zeros((3,3))
# print(arr1)

# 2 fill all element with zeros
# arr2 =np.ones((3,3))
# print(arr2)

# 3 fill element with random number 
# arr_random = np.full((3,3),5)
# arr_random2 = np.full((3,3),800)
# print(arr_random)
# print(arr_random2)

# 4.----> make indentity matrix 
# arr_eye1 = np.eye(4)
# arr_eye2 = np.eye(6)
# print(arr_eye1)
# print(arr_eye2)

# 5. arange all the element into 1D array 
# arr_arange= np.arange(1,10,2)
# print(arr_arange)
# print(arr_arange.ndim)
# print(arr_arange.dtype)

arr= np.zeros((2,3))
print(arr.shape)
print(arr)
arrmew=arr.reshape((3,2))
print(arrmew.shape)
print(arrmew)




# falterring in array
arr1d= np.ones((3,4))
print(arr1d)
newar= arr1d.flatten()
print(newar)












(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]
(3, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
